### ISSUE TITLE
Lando Engine API Documentation confusion

### ISSUE THREAD

**Issue by Xilonz** [lando/docs#11]
While working on a custom tooling command I found out that the Lando engine API documentation is (completely?) wrong or confusing.

https://docs.lando.dev/api/engine.html#lando-engine-run-data-%E2%87%92-promise

Insead of:
```js
return lando.engine.run({
  id: 'myapp_database_1',
  cmd: ['bash'],
  opts: {
    mode: 'attach'
  }
});
```

Something like this is required I think, this is what, for example, the ssh task looks to be doing something similar like this:
```js
const app = lando.getApp(root, false);
return lando.engine.run({
  compose: app.compose,
  project: app.project,
  cmd: [ 'bash'],
  opts: {
    mode: 'attach',
    services: ['appserver'],
   }
});
```

**Comment by reynoldsalec** [comment]
The API docs were removed because they're out-of-date; they need to be revisited for Lando 4.x.

For now, I made a commit to remove the API link in the footer (one of the last remaining API links) to prevent future confusion.
