### ISSUE TITLE
Responsive Docs: Special Sponsors sidebar covering site content

### ISSUE THREAD

**Issue by lguima** [lando/docs#13]
**Pages that need to be updated or changed.**
Every documentation page like: https://docs.lando.dev/basics/

**Actual result**
The Special Sponsors sidebar is covering the site content in 1366x768 (16:9) resolution.

**Expected result**
The Special Sponsors sidebar do not cover the site content in any resolution.

![lando](https://user-images.githubusercontent.com/1562097/117008595-46b71000-acc1-11eb-8f44-d53de5e613ee.png)

**Comment by reynoldsalec** [comment]
The docs don't have great responsive support, which apparently includes smaller desktop displays.

I don't think it'll be a priority, but we'll be introducing a new docs theme in the New Year as we approach Lando 4.x. Going to leave this as a reminder, but we should close it out sometime in 2022.

**Comment by lguima** [comment]
@reynoldsalec I'm closing it since the new layout is pretty responsive and the issue no longer happens. Thanks!
