### ISSUE TITLE
Write tutorial on using browsersync with lando

### ISSUE THREAD

**Issue by pirog** [lando/docs#130]
Let's write a tutorial (https://github.com/kalabox/lando/tree/master/docs/tutorials) that a user can follow so that when they are done reading they have a good idea of how to use things like browsersync with lando. this should cover

1. linking to front end tooling set up to get going
2. exposing relevant browersync ports
3. editing relevant browserync config

**Comment by tanc** [comment]
@chrillep did you ever figure out the form submission issue where submitting a form leads to the appserver domain instead of the proxied domain?
