### ISSUE TITLE
Apache config files links are not working

### ISSUE THREAD

**Issue by arnoldski** [lando/docs#15]
Please complete the following:

**Link to the page that needs to be updated or changed.**
https://docs.lando.dev/config/apache.html#using-custom-apache-config-files

**Describe the change you'd like**
In the first sentence there is a link to Github that doesn't exist anymore: https://github.com/lando/lando/tree/main/plugins/lando-services/services/apache.

Also this link in Google is not working: https://github.com/lando/lando/blob/main/plugins/lando-services/services/apache/httpd.conf

**Comment by reynoldsalec** [comment]
Updated with the new location: https://github.com/lando/docs/commit/006eabb53d96c256ee1559ee1b31901ab8cfe979
