### ISSUE TITLE
Lando build documentation is out-of-date

### ISSUE THREAD

**Issue by dmp1ce** [lando/docs#16]
**Link to the page that needs to be updated or changed.**
https://github.com/lando/lando/blob/main/docs/contrib/contrib-building.md

**Describe the change you'd like**
I cannot build lando with these steps on Arch Linux. I looked through the code myself but couldn't figure out how to build lando. Is lando built with lando?

**Comment by reynoldsalec** [comment]
I think it's out of date; looks like the command is now `build:cli`: https://github.com/lando/cli/blob/main/package.json#L36

**Comment by dmp1ce** [comment]
I get the error:

```
yarn run v1.22.17
error Command "build:cli" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by reynoldsalec** [comment]
Ok, updated the docs with the new instructions for building Lando from source: https://github.com/lando/docs/blob/main/docs-3.x/contrib/contrib-building.md

Note that I've stripped out the installer build instructions, since those have gotten less automated/more complex in splitting up the Lando monorepo.

**Comment by dmp1ce** [comment]
Following the docs from https://github.com/lando/docs/blob/main/docs-3.x/contrib/contrib-building.md I got the error below. I'm not sure if I missed a prior step.

```
david@bar:~/Workspace/lando-cli$ yarn run build:cli
yarn run v1.22.17
$ yarn clean && yarn pkg -c package.json -t node14 bin/lando.js
$ rimraf dist
/bin/sh: line 1: rimraf: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by reynoldsalec** [comment]
@dmp1ce did you run `yarn install`?

Apologies for the late reply, US holidays got in the way.

**Comment by dmp1ce** [comment]
Yeah. When I use the [correct repository](https://github.com/lando/cli) and I use `yarn install` (which is not in the documentation) then `yarn run build:cli` it builds correctly!
