### ISSUE TITLE
Lando PHP-FPM / Pool config settings

### ISSUE THREAD

**Issue by Preen** [lando/docs#17]
Please complete the following:

**Link to the page that needs to be updated or changed.**
https://docs.lando.dev/config/wordpress.html#getting-started

**Describe the change you'd like**
I cant find any documentation on how to change the php-fpm pool config files. I have to manually ssh into the container changing it as root user. Where do I define settings for either FPM config or fpm-pool config?

**Comment by reynoldsalec** [comment]
@labboy0276 this might be super simple for you; very low priority but assign yourself and knock it out if you have a clue.

**Comment by labboy0276** [comment]
@Preen It is possible to add certain config files via https://docs.lando.dev/config/php.html#configuration

If that doesn't do the trick, then you can do what you need to on `build_as_root` like [this blog article](https://ericpugh.dev/2020/my-drupal-lando-config/) mentions.  

If either of these don't do the trick, please re-open and we can discuss more.

**Comment by reynoldsalec** [comment]
@labboy0276 do you have any experience using `php-fpm.conf` with Lando? I see the OP's point that we don't have instructions...if you think that blog article is the best instructions, it might be a target for a guide or other mention in the docs.

**Comment by labboy0276** [comment]
No I have only set vhosts and php.ini based stuffs @reynoldsalec

**Comment by reynoldsalec** [comment]
Ok, I'm going to reopen this, it's probably not a hot-button issue seeing as it hasn't come up outside of this issue, but seems like a good addition.

**Comment by tormi** [comment]
I described it here:https://github.com/lando/php/issues/108.

**Comment by reynoldsalec** [comment]
Good catch @tormi, thanks for referencing this! Going to close this out...I suspect we may directly address this as a feature/document it as such, but for now you can track progress on https://github.com/lando/php/issues/108
