### ISSUE TITLE
API doc is not available

### ISSUE THREAD

**Issue by lolautruche** [lando/docs#18]
The API doc, which should be accessible from the top menu, is not available.
Clicking on the menu entry, pointing to https://docs.lando.dev/api/app.html, leads to a 404.
![image](https://user-images.githubusercontent.com/313528/124729387-b095a500-df10-11eb-8e3f-1442fab70d83.png)

![image](https://user-images.githubusercontent.com/313528/124729549-d3c05480-df10-11eb-8003-a5198bbfcc75.png)

**Comment by reynoldsalec** [comment]
The API docs were removed because they're out-of-date; they need to be revisited for Lando 4.x.

For now, I made a commit to remove the API link in the footer (one of the last remaining API links) to prevent future confusion.
