### ISSUE TITLE
Should I stay on 3.20.8?

### ISSUE THREAD

**Issue by MatthiasBrodelet** [lando/docs#276]
First off want to say that I am super grateful for this project and it has simplified local development in ways I could have never imagined.

However I am a little bit confused because I have been getting the "update available" message in the CLI for a while now.
And it always is a beta release.
Should I stay on version 3.20.8 until the next stable release?
I (obviously) use this for work so I don't really have time to experiment with beta's.
When can we expect the next stable release?

**Comment by reynoldsalec** [comment]
@MatthiasBrodelet here's a broader explanation of what's up with the unconventional/inconvenient beta-as-recommended release we have temporarily: https://github.com/lando/lando/issues/3666#issuecomment-1953213246

I believe the stable will be released when the [new installation scripts](https://docs.lando.dev/install/macos.html) are all finalized; the lingering item there were the Windows install scripts, which were [merged yesterday](https://github.com/lando/setup-lando/pull/17), so I would anticipate a stable release in the next week or two, with the caveat that I'm an optimistic person 😉 

That said, I don't see much substantive changing about the release, so what you install now will probably be pretty similar to the "stable" release.

Going to close this out, but definitely feel free to follow up here or on Slack if you have any more questions!
