### ISSUE TITLE
Broken link in v3/services page

### ISSUE THREAD

**Issue by kayakr** [lando/docs#277]
https://docs.lando.dev/core/v3/services.html has a link to "build steps" with href to `./lando-service.html` but this resolves to https://docs.lando.dev/core/v3/lando-service.html and 404s. Should the link be to `#lando-service`?

But then in https://docs.lando.dev/core/v3/services.html#lando-service there is a further link to "Build Steps", again to `./lando-service.html` and this also 404s. Are Build steps gone in v3?

**Comment by kayakr** [comment]
I guess these should be linking to https://docs.lando.dev/core/v3/services/lando.html#build-steps

**Comment by reynoldsalec** [comment]
@kayakr thanks for making an issue, should be resolved now!
