### ISSUE TITLE
add "lando urls" or "lando vitals" command

### ISSUE THREAD

**Issue by lsmith77** [lando/docs#47]
Please complete the following:

**Link to the page that needs to be updated or changed.**
https://docs.lando.dev/basics/usage.html

**Describe the change you'd like**
A command that lists the URLs shown at the very end when starting up lando containers. Especially for serivces with dynamic urls (like mailhog) this would be nice to have, since extracting this out of `lando info` is tedious.

```
$ lando urls
 APPSERVER_NGINX URLS  https://localhost:33278
                       http://localhost:33279
                       http://foo.lndo.site/
                       https://foo.lndo.site/
 MAILHOG URLS          http://localhost:33280
```

It could also be everything shown at the very end .. ie

```
$ lando vitals
Here are some vitals:

 NAME                  recruit
 LOCATION              /home/bar/foo
 SERVICES              appserver_nginx, appserver, database, node, mailhog
 APPSERVER_NGINX URLS  https://localhost:33278
                       http://localhost:33279
                       http://foo.lndo.site/
                       https://foo.lndo.site/
 MAILHOG URLS          http://localhost:33280
```

**Comment by james0r** [comment]
This is admittedly a silly workaround, but I just run `lando start` again at the end of my bash script, it sees everything is running then gives me my urls.
