### ISSUE TITLE
Update VSCODE documentation for xdebug 3

### ISSUE THREAD

**Issue by that0n3guy** [lando/docs#5]
**Link to the page that needs to be updated or changed.**
https://docs.lando.dev/guides/lando-with-vscode.html

**Describe the change you'd like**
There is a bunch of stuff that needs updated on this page.  Here is a quick list:

* in lando.yml:   `xdebug: debug` (instead of `true`, thought i'm not sure if it makes a difference), also the config vs conf got me for a long time
* the default port change in `.vscode/launch.json` to 9003 instead of 9000
* in php.ini:

```
[PHP]

; Xdebug
xdebug.mode=debug ; it didn't work without this
xdebug.start_with_request = yes
xdebug.client_host = ${LANDO_HOST_IP}
xdebug.log = /tmp/xdebug.log
```

**Comment by reynoldsalec** [comment]
I think pretty much all of these changes were incorporated sometime since the OP.

@musicaljoeker I like that suggestion, but a little worried that suggesting that low of a setting might prevent people from getting some useful messages? Don't know what your experience has been.
