### ISSUE TITLE
The Ghost CMS example in MEAN recipe doesn't work

### ISSUE THREAD

**Issue by paulpopus** [lando/docs#6]
Maybe I messed up somewhere, but I've been trying to get Ghost to work in lando and I tried the MEAN example to figure out what I'm doing wrong but the code example there doesn't lead to a working example of Ghost running. I'm on the latest lando, perhaps something in Ghost changed since that code was written?

**Link to the page that needs to be updated or changed.**
https://docs.lando.dev/config/mean.html#getting-started

**Describe the change you'd like**
Copy the code example and have Ghost running in lando.

**Comment by reynoldsalec** [comment]
Tested current version of docs and looks like the instructions work...only difference I saw between them and the https://github.com/lando/cli/tree/main/examples/mean version was including `--option node=14` in the `lando init` and a slight variation in how they install ghost (running `ghost install` with the `--no-start` flag vs. running an explicit `ghost stop`)
