### ISSUE TITLE
PHPStorm Unit testing with MySQL error 'getaddrinfo failed: Name or service not known'

### ISSUE THREAD

**Issue by basepack** [lando/docs#7]
Getting this error while PHPUnit testing in PHPStorm and use a MySQL test database? 
`Illuminate\Database\QueryException : SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known`

Well it is already in the docs [here](https://docs.lando.dev/guides/external-access.html#mapping-to-the-lando-network), only did I find it after 8 hours of debugging Laravel/Docker/Lando settings. So I thought it should be fair to document it here too, as this was the place I was looking first to see if someone else had experienced this already. 

I cannot count the amount of times I ran `lando destroy & lando rebuild -y` and `docker system prune -a --volumes`.

But it was a simple thing after all: your docker `appserver` container is somehow separated from your `database` container when running PHPUnit in PHPStorm.

To fix it, see [here](https://docs.lando.dev/guides/external-access.html#mapping-to-the-lando-network), or follow the convenient screenshots guide from me below:

For this example I use a Lando project that is called `lando-laravel` and therefor the network name is called `landolaravel_default` for me, yours will be different.

**Step 1** 
Run `docker network ls' and get your network name: 
![image](https://user-images.githubusercontent.com/939500/104576993-3e2ac300-5659-11eb-91f0-afa62197adc9.png)

**Step 2**
Go to `PHPStorm Settings > Languages & Frameworks > PHP > Test Frameworks` and click the little folder next to `Docker container:`:
![image](https://user-images.githubusercontent.com/939500/104577395-bd1ffb80-5659-11eb-8aa3-f6c56565dda1.png)

**Step 3**
Fill in the networkname you found earlier:
![image](https://user-images.githubusercontent.com/939500/104577557-ec366d00-5659-11eb-8fa1-0498261c41ca.png)

**Great! 😁**
![image](https://user-images.githubusercontent.com/939500/104577749-2142bf80-565a-11eb-8891-837703e9c7d1.png)

**Comment by reynoldsalec** [comment]
I added a reference to this specific error in the docs, going to close this out but hopefully the combination of this issue and the docs will help others!

**Comment by firecentaur** [comment]
Thank you so much for this post !! It helped me get my docker working!

**Comment by ghaskell** [comment]
Thank you so much.  This was still a huge help!

**Comment by paramsave** [comment]
Thank you!!!

**Comment by ptelevich** [comment]
Thank you!

**Comment by appershan** [comment]
I don't see any options for a docker image:
![jol8zuine22o](https://user-images.githubusercontent.com/105047594/236772220-47a9a8af-7054-4219-a576-a8eba0c0db27.png)

This is because by default PHP Storm creates a Local interpreter. Remove this and add a remote interpreter, instead:
![image](https://user-images.githubusercontent.com/105047594/236769172-95e8c2db-a61b-426b-b2fd-da14f1d5ad87.png)

You have to choose the correct Docker container:
![scrc1gbopw1n](https://user-images.githubusercontent.com/105047594/236772280-1a717804-cc34-4c02-9f44-0338bf4cc6ed.png)

After that you can follow @basepack their instructions and everything works!

**Comment by franciscorjr** [comment]
thank you very much!!! 
helped a lot.

**Comment by franciscorjr** [comment]
> I don't see any options for a docker image: ![jol8zuine22o](https://user-images.githubusercontent.com/105047594/236772220-47a9a8af-7054-4219-a576-a8eba0c0db27.png)
> 
> This is because by default PHP Storm creates a Local interpreter. Remove this and add a remote interpreter, instead: ![image](https://user-images.githubusercontent.com/105047594/236769172-95e8c2db-a61b-426b-b2fd-da14f1d5ad87.png)
> 
> You have to choose the correct Docker container: ![scrc1gbopw1n](https://user-images.githubusercontent.com/105047594/236772280-1a717804-cc34-4c02-9f44-0338bf4cc6ed.png)
> 
> After that you can follow @basepack their instructions and everything works!

try to install and enable Docker and PHP Docker plugin in your PHPStorm IDE.

**Comment by dgpro** [comment]
I had `bridge` in Network mode setting which appears in the list but it worked only when I changed it to `local_network` which is an actual name of the network in docker file.
`
$ docker network ls
NETWORK ID     NAME                 DRIVER    SCOPE
6cf07ea650a0   bridge               bridge    local
3824a3e9e38c   host                 host      local
1d310e94a7a4   local_network   bridge    local
acfdd57f7273   none                 null      local
`
